# ========================
#  SITE CORE CONFIGURATION
# ========================
title: "Synapse Knowledge Hub"
description: "Curated insights with affiliate recommendations for AI, tech, and cognitive science"
baseurl: "" # For project repos, use '/repository-name'
url: "https://yourusername.github.io" # Replace with your GitHub Pages URL

# =================
#  MONETIZATION SETTINGS
# =================
affiliates:
  amazon:
    tracking_id: "YOUR_AMAZON_ASSOCIATE_ID" # From Amazon Associates
    auto_disclaimer: true
  bookshop:
    affiliate_id: "YOUR_BOOKSHOP_ID"
  ko-fi:
    username: "yourkofiusername"
    button_color: "#29abe0"

# =================
#  CONTENT STRUCTURE
# =================
collections:
  curated_resources:
    output: true
    permalink: /resources/:path/
  premium_guides:
    output: true
    permalink: /premium/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      monetization: true # Enables affiliate sections

# =================
#  TECHNICAL SETTINGS
# =================
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

paginate: 5
paginate_path: "/blog/page:num/"

# =================
#  PERFORMANCE OPTIMIZATION
# =================
compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false

# =================
#  SEO CONFIGURATION
# =================
seo:
  title_separator: "|"
  social:
    name: "Synapse Knowledge Hub"
    links:
      - "https://twitter.com/yourhandle"
      - "https://github.com/yourusername"

# =================
#  CUSTOM VARIABLES
# =================
theme_settings:
  primary_color: "#4f46e5"
  dark_mode: true
  typography:
    header_font: "Helvetica, sans-serif"
    body_font: "Georgia, serif"

author:
  name: "Your Name"
  bio: "Curator of interconnected ideas"
  email: "your@email.com"
  social_links:
    github: yourusername
    twitter: yourhandle

# =================
#  SAFE MODE FOR GITHUB
# =================
safe: true
whitelist: [jekyll-paginate, jekyll-seo-tag]